deployment:
  kind: Deployment
  podAnnotations:
    prometheus.io/port: "9100"
    prometheus.io/scrape: "true"
  podLabels:
    gke: traefik
  replicas: 3
ingressClass:
  enabled: true
  fallbackApiVersion: ""
  isDefaultClass: false
  name: traefik-external
ingressRoute:
  dashboard:
    enabled: false
metrics:
  prometheus:
    addEntryPointsLabels: false
    addServicesLabels: false
    entryPoint: metrics
nodeSelector:
  cloud.google.com/gke-container-runtime: containerd
ports:
  metrics:
    exposedPort: 9100
  traefik:
    exposedPort: 9000
  web:
    redirectTo:
      port: "websecure"
    expose: 
      enabled: true  # Changed from expose: true
    exposedPort: 80
    port: 80
  websecure:
    expose: 
      enabled: true  # Changed from expose: true
    exposedPort:
    # https://www.cloudflare.com/th-th/ips/
    forwardedHeaders:
      trustedIPs:
      - 103.21.244.0/22
      - 103.22.200.0/22
      - 103.31.4.0/22
      - 104.16.0.0/13
      - 104.24.0.0/14
      - 108.162.192.0/18
      - 131.0.72.0/22
      - 141.101.64.0/18
      - 162.158.0.0/15
      - 172.64.0.0/13
      - 173.245.48.0/20
      - 188.114.96.0/20
      - 190.93.240.0/20
      - 197.234.240.0/22
      - 198.41.128.0/17
      - 2400:cb00::/32
      - 2606:4700::/32
      - 2803:f800::/32
      - 2405:b500::/32
      - 2405:8100::/32
      - 2a06:98c0::/29
      - 2c0f:f248::/32
    port: 443
providers:
  kubernetesCRD:
    ingressClass: traefik-external
    allowExternalNameServices: true
    enabled: true
  kubernetesIngress:
    allowExternalNameServices: true
    enabled: true
    ingressEndpoint:
      publishedService: traefik/traefik
resources:
  limits:
    cpu: "2"
    memory: 8Gi
  requests:
    cpu: 100m
    memory: 128Mi
securityContext:
  capabilities:
    add:
    - NET_BIND_SERVICE
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0
service:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    networking.gke.io/load-balancer-type: External
  enabled: true
  type: LoadBalancer

rbac:
  enabled: true

globalArguments:
  - --api.insecure=true
  - --global.sendanonymoususage=false
  - --global.checknewversion=false

additionalArguments:
 - --global.checknewversion=false
 - --api=true
 - --api.dashboard=true
 - --accesslog=true
 - --accesslog.format=json
 - --accesslog.fields.defaultmode=keep
 - --accesslog.fields.headers.defaultmode=drop
 - --log.level=info
 - --entrypoints.web.address=:80
 - --entrypoints.websecure.address=:443
 - --entryPoints.traefik.address=:9000
 - --entryPoints.metrics.address=:9100
 - --entrypoints.web.http.redirections.entryPoint.to=websecure
 - --entrypoints.web.http.redirections.entryPoint.scheme=https
 - --entrypoints.web.http.redirections.entrypoint.permanent=true
 - --ping
 - --providers.kubernetesingress
 - --providers.kubernetescrd
 - --metrics.prometheus=true
 - --metrics.prometheus.entryPoint=metrics
 - --serversTransport.insecureSkipVerify=true